import { FifaTeamConfig, FifaCardItem } from './types';

export const TEAMS_DATA: Record<string, FifaTeamConfig> = {
  real: {
    id: 'real',
    name: 'Реал Мадрид (с Авито)',
    shortName: 'РЕАЛ',
    primaryColor: '#ffffff',
    secondaryColor: '#f59e0b',
    textColor: '#1e293b',
    flag: '👑',
    stadiumName: 'Сантьяго Картонка',
    description: 'Все игроки куплены на барахолке, но апломб как у 15-кратных чемпионов.',
    rating: 88,
    anthemNote: 440,
  },
  barca: {
    id: 'barca',
    name: 'Барселона (в Кредите)',
    shortName: 'БАРСА',
    primaryColor: '#b91c1c',
    secondaryColor: '#1d4ed8',
    textColor: '#ffffff',
    flag: '🔴🔵',
    stadiumName: 'Камп Ноу (в ремонте до 2045)',
    description: 'Активировали 14-й экономический рычаг, чтобы купить хотя бы мяч.',
    rating: 87,
    anthemNote: 494,
  },
  gazmyas: {
    id: 'gazmyas',
    name: 'ГазМяс (Омск)',
    shortName: 'ГАЗМЯС',
    primaryColor: '#dc2626',
    secondaryColor: '#f97316',
    textColor: '#ffffff',
    flag: '🥩',
    stadiumName: 'Омский Заводской Пустырь',
    description: 'Тренер Михалыч обещал закопать команду живьем за поражение со счетом менее 0:8.',
    rating: 58,
    anthemNote: 330,
  },
  manchester: {
    id: 'manchester',
    name: 'Манчестер Не-Юнайтед',
    shortName: 'МЮ',
    primaryColor: '#dc2626',
    secondaryColor: '#111827',
    textColor: '#ffffff',
    flag: '👹',
    stadiumName: 'Олд Травостой',
    description: 'Магуайр капитан, защита в панике, фанаты плачут с 2013 года.',
    rating: 79,
    anthemNote: 392,
  },
  brazil: {
    id: 'brazil',
    name: 'Бразилия 2002 (Все Лысые)',
    shortName: 'БРА',
    primaryColor: '#facc15',
    secondaryColor: '#15803d',
    textColor: '#15803d',
    flag: '🇧🇷',
    stadiumName: 'Маракана в фавелах',
    description: 'Роналдо с челкой, Роналдиньо улыбается, самба нон-стоп!',
    rating: 93,
    anthemNote: 523,
  },
  dvor: {
    id: 'dvor',
    name: 'Сборная Двора №5',
    shortName: 'ДВОР',
    primaryColor: '#0ea5e9',
    secondaryColor: '#64748b',
    textColor: '#ffffff',
    flag: '🏚️',
    stadiumName: 'Коробка между гаражами',
    description: 'Кто дальше пнёт мяч в окно тети Гали — тот и выбивает.',
    rating: 72,
    anthemNote: 370,
  },
  pensioners: {
    id: 'pensioners',
    name: 'Ветераны ЖЭКа',
    shortName: 'ЖЭК',
    primaryColor: '#15803d',
    secondaryColor: '#eab308',
    textColor: '#ffffff',
    flag: '👴',
    stadiumName: 'Лавочка у подъезда',
    description: 'Тактика: лечь на газон, схватиться за поясницу и требовать валидол.',
    rating: 64,
    anthemNote: 293,
  },
  france: {
    id: 'france',
    name: 'Франция (В Черепашьих Масках)',
    shortName: 'ФРА',
    primaryColor: '#1e3a8a',
    secondaryColor: '#ffffff',
    textColor: '#ffffff',
    flag: '🥐',
    stadiumName: 'Стад де Багет',
    description: 'Мбаппе бежит быстрее звука, остальные едят круассаны.',
    rating: 91,
    anthemNote: 466,
  }
};

export const CURSED_CARDS: FifaCardItem[] = [
  {
    id: 'card_ronaldo',
    name: 'Криштиану Ронулду',
    nick: 'КРИРО С БАЗАРА',
    rating: 99,
    role: 'FWD',
    team: 'Реал Мадрид (с Авито)',
    rarity: 'gold',
    avatarEmoji: '🤴',
    specialSkill: 'Крик «СИУУУ!» глушит вратаря на 5 секунд',
    quote: 'Я забиваю только тогда, когда зеркало рядом!',
    stats: { pac: 98, sho: 99, pas: 65, dri: 92, def: 20, phy: 90 },
  },
  {
    id: 'card_messi',
    name: 'Лионель Пепси',
    nick: 'ГНОМ-ВОЛШЕБНИК',
    rating: 98,
    role: 'FWD',
    team: 'Барселона (в Кредите)',
    rarity: 'gold',
    avatarEmoji: '🐐',
    specialSkill: 'Дриблинг сквозь ноги судьи и фотографов',
    quote: 'Куда делись все мои золотые мячи? На металлолом сдал?',
    stats: { pac: 89, sho: 96, pas: 98, dri: 99, def: 30, phy: 55 },
  },
  {
    id: 'card_maguire',
    name: 'Гарри Магуайр',
    nick: 'ХОЛОДИЛЬНИК 5000',
    rating: 52,
    role: 'DEF',
    team: 'Манчестер Не-Юнайтед',
    rarity: 'cursed',
    avatarEmoji: '🗿',
    specialSkill: 'Случайный автогол в девятку своих ворот',
    quote: 'Защита — это когда ты стоишь и думаешь о смысле бытия.',
    stats: { pac: 15, sho: 70, pas: 40, dri: 25, def: 50, phy: 99 },
  },
  {
    id: 'card_neymar',
    name: 'Неймар Джуниор',
    nick: 'АКТЁР БОЛЬШИХ ТЕАТРОВ',
    rating: 89,
    role: 'FWD',
    team: 'Бразилия 2002 (Все Лысые)',
    rarity: 'silver',
    avatarEmoji: '🎭',
    specialSkill: 'Катится по полю 45 метров после любого контакта',
    quote: 'Ауч! Мне наступили на тень! Где носилки?!',
    stats: { pac: 91, sho: 84, pas: 86, dri: 95, def: 25, phy: 12 },
  },
  {
    id: 'card_haaland',
    name: 'Эрлинг Киборг',
    nick: 'ХОЛОДИЛЬНИК НА БАТАРЕЙКАХ',
    rating: 96,
    role: 'FWD',
    team: 'Сборная Двора №5',
    rarity: 'gold',
    avatarEmoji: '🤖',
    specialSkill: 'Пробивает сетку ворот вместе с вратарём',
    quote: '01010011 01001111 01000011 01000011 01000101 01010010!',
    stats: { pac: 95, sho: 98, pas: 65, dri: 80, def: 45, phy: 99 },
  },
  {
    id: 'card_dzyuba',
    name: 'Артём Дзюба',
    nick: 'ОПЕРАТОР КАМЕРЫ',
    rating: 74,
    role: 'FWD',
    team: 'ГазМяс (Омск)',
    rarity: 'bronze',
    avatarEmoji: '📱',
    specialSkill: 'Длинная передача прямо в руки милиции',
    quote: 'Я просто видео снимал, какой пенальти?!',
    stats: { pac: 45, sho: 78, pas: 68, dri: 60, def: 35, phy: 88 },
  },
  {
    id: 'card_tolya',
    name: 'Дядя Толя (Вратарь)',
    nick: 'СТЕНА ИЗ КИРПИЧА И ПИВА',
    rating: 61,
    role: 'GK',
    team: 'Ветераны ЖЭКа',
    rarity: 'cursed',
    avatarEmoji: '🍺',
    specialSkill: 'Отбивает мячи пузом и трехэтажным матом',
    quote: 'Кто разбил стекло в шестом подъезде?! Мяч конфискован!',
    stats: { pac: 20, sho: 30, pas: 40, dri: 15, def: 75, phy: 95 },
  },
  {
    id: 'card_referee',
    name: 'Судья Карасёв на Пенсии',
    nick: 'ЧЕЛОВЕК СО СВИСТКОМ',
    rating: 100,
    role: 'MID',
    team: 'Сборная Двора №5',
    rarity: 'cursed',
    avatarEmoji: '🕶️',
    specialSkill: 'Красная карточка за то, что игрок дышал в его сторону',
    quote: 'За 500 рублей это чистый гол, за 1000 — пенальти!',
    stats: { pac: 75, sho: 80, pas: 90, dri: 70, def: 99, phy: 80 },
  },
  {
    id: 'card_mbappe',
    name: 'Килиан Черепашка',
    nick: 'ТУРБО-ДОНАТЕЛЛО',
    rating: 97,
    role: 'FWD',
    team: 'Франция (В Черепашьих Масках)',
    rarity: 'gold',
    avatarEmoji: '🐢',
    specialSkill: 'Убегает за пределы экрана и возвращается с голом',
    quote: 'Я подпишу контракт с клубом только если мне подарят Эйфелеву башню.',
    stats: { pac: 99, sho: 94, pas: 82, dri: 94, def: 36, phy: 78 },
  },
];

export const FUNNY_COMMENTARIES = [
  "Василий Уткин: «Я видел много плохих ударов, но этот мяч улетел на Марс кормить марсоход!»",
  "Георгий Черданцев: «ДА ЛАДНО?! ОН НЕ ПОПАЛ В ПУСТЫЕ ВОРОТА С ПОЛУМЕТРА?! Я УХОЖУ ИЗ ЭФИРА!»",
  "Судья в рупор: «Так, пацаны, мяч улетел в крапиву, кто выбьет — тот бьёт угловой!»",
  "Голос со стадиона: «Судью на мыло! Судью на колбасу! Дай карточку!»",
  "Комментатор: «Игрок упал... Никакого контакта не было, он просто устал жить!»",
  "VAR-центр: «Мы посмотрели повтор с домофона. Ничего не понятно, пусть перебивают!»",
  "Тренер Михалыч: «Гаврилов, ты в футбол играешь или балет репетируешь?! Бегом назад!»",
  "EA Sports: «Чтобы разблокировать попадание по воротам, оплатите $19.99 в магазине!»",
  "Зритель с трибуны: «Эй, отдайте мяч, это мой сынок со двора принёс!»",
  "Комментатор: «Вратарь сделал вид, что прыгнул, но гравитация сказала твердое нет.»",
  "Диктор: «Внимание! На поле выбежала дворовая собака и отобрала мяч у нападающего!»",
  "Судья: «Я потерял свисток, поэтому просто громко кричу: УИИИИИИ!»"
];
